#include "../NewCodeGenerator.h"

void NewCodeGenerator::visit(LoopStatement& node) {
    debug_print("Visiting LoopStatement node (NOTE: branching is handled by block epilogue).");
    // This visitor is now intentionally empty.
    // The presence of the LoopStatement in the AST has already been used by the
    // CFGBuilderPass to correctly terminate the current basic block and add an
    // edge to the loop header. The actual branch instruction is generated by
    // `generate_block_epilogue` based on the CFG.
}
