#include "LabelManager.h"
#include "NewCodeGenerator.h"
#include "analysis/ASTAnalyzer.h"
#include <iostream>
#include <stdexcept>

void NewCodeGenerator::visit(GotoStatement &node) {
  debug_print("Visiting GotoStatement node (NOTE: branching is handled by "
              "block epilogue).");
  // This visitor is now intentionally empty.
  // The presence of the GotoStatement in the AST has already been used by the
  // CFGBuilderPass to correctly terminate the current basic block.
  // The actual branch instruction is generated by `generate_block_epilogue`
  // based on the successor edges in the CFG.
}
