#include "../NewCodeGenerator.h"

void NewCodeGenerator::visit(BreakStatement& node) {
    debug_print("Visiting BreakStatement node (NOTE: branching is handled by block epilogue).");
    // This visitor is now intentionally empty.
    // The presence of the BreakStatement in the AST has already been used by the
    // CFGBuilderPass to correctly terminate the current basic block and add an
    // edge to the loop exit. The actual branch instruction is generated by
    // `generate_block_epilogue` based on the CFG.
}
